[build]
builder = "nixpacks"
nixpacksConfigPath = "../../nixpacks.toml"
watchPatterns = ["apps/web/**", "packages/**", "nixpacks.toml", "turbo.json", "package.json", "pnpm-lock.yaml"]

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[service]
internalPort = 3000
