[build]
builder = "dockerfile"
dockerfilePath = "../../Dockerfile"

[deploy]
startCommand = "./start.sh"
healthcheckPath = "/api/v1/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[service]
internalPort = 3001
