[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile.control-plane"

[deploy]
healthcheckPath = "/api/v1/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[service]
internalPort = 3001
